In [1]:
import pandas as pd
import seaborn as sns

In [2]:
label_df = pd.read_pickle('../data/prepared/label_df.pickle')

In [3]:
label_df

,make,model,year,msrp,front_wheel_size_in,sae_net_horsepower_rpm,displacement,engine_type,width_max_wo_mirrors_in,height_overall_in,length_overall_in,gas_mileage,drivetrain,passenger_capacity,passenger_doors,body_style,id
0,Ford,Flex,2010,39,19,260,35,6,75,68,201,16,AWD,7,4,4dr,Zza.jpg
1,Chevrolet,Suburban,2011,41,17,320,53,8,79,76,nan,15,RWD,9,4,SUV,hyG.jpg
2,Nissan,Maxima,2011,31,18,290,35,6,73,57,190,19,FWD,5,4,4dr,Ytw.jpg
3,Chevrolet,Silverado 1500,2014,45,20,350,53,8,80,74,nan,16,RWD,5,4,Pickup,Fhi.jpg
4,Dodge,Durango,2019,45,20,290,36,6,75,70,201,18,AWD,6,4,SUV,usz.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64462,Subaru,Forester,2016,29,18,250,20,4,70,68,180,23,AWD,5,4,SUV,KnV.jpg
64463,GMC,Acadia,2011,45,20,280,36,6,78,69,200,16,AWD,7,4,SUV,tug.jpg
64464,Porsche,718,2019,82,20,360,25,4,70,50,173,19,RWD,2,2,Convertible,YpY.jpg
64465,Subaru,Outback,2016,24,17,170,25,4,72,66,189,25,AWD,5,4,SUV,NAc.jpg
64466,Volkswagen,Tiguan,2019,25,17,180,20,4,72,66,185,21,AWD,5,4,SUV,Mzf.jpg

In [5]:
# Images per make
label_df.make.value_counts()

Chevrolet        5079
Toyota           4598
Ford             4416
BMW              4121
Nissan           3881
Audi             3131
Mercedes-Benz    3097
Honda            2675
Kia              2160
Lexus            2125
Hyundai          2091
GMC              2067
Volkswagen       1752
Subaru           1605
Mazda            1475
Dodge            1345
Porsche          1344
Lincoln          1324
Cadillac         1311
Volvo            1231
Jeep             1196
Acura            1174
Jaguar           1062
MINI             1059
Buick             964
Land Rover        960
INFINITI          917
FIAT              892
Ram               747
Bentley           697
Mitsubishi        644
Aston Martin      574
Chrysler          570
Maserati          449
smart             386
Alfa Romeo        290
Rolls-Royce       277
Lamborghini       251
Tesla             191
Genesis           176
Ferrari            91
McLaren            72
Name: make, dtype: int64

In [25]:
# Images per make and model
label_df.groupby(['make', 'model']).size()

make   model
Acura  ILX       176
       MDX       293
       NSX       210
       RDX       188
       RLX       182
                ...
Volvo  V90        62
       XC40       55
       XC60      191
       XC90      332
smart  fortwo    386
Length: 323, dtype: int64