In [19]:
import os
import re
import pandas as pd

In [20]:
def open_file_structure(path, clean=True):
    """
    Open and prepare file structure
    """
    with open(path) as f:
        structure = f.read()
        
    structure = [x.replace("'", "") for x in structure.split("', ")]
    
    if clean:
        # Tolower, remove special characters and whitespaces
        structure = [x.lower() for x in structure]
        structure = [re.sub('[^a-zA-Z0-9 \n\.]', '', x) for x in structure]
        structure = [x.replace(' ', '_') for x in structure]
        structure = [x.replace('__', '_') for x in structure]

    return structure

In [31]:
def expand_column(df, column, col_names):
    """
    Extract columns for single string
    """
    df_expanded = pd.DataFrame(df[column].str.split('_', expand=True))
    df_expanded.columns = [*col_names, 'id']
    return df_expanded

In [32]:
# Change working dir to data folder 
os.chdir('/Users/fabianmueller/Intern/Projekte/Car-Classifier/data')

In [33]:
# Get jpg-files in raw folder
files = [file for file in os.listdir('raw') if file.endswith(".jpg")]

# Get file structure
file_name_components = open_file_structure('label_structure.txt', True)

# Create lookup table containing multiple information about images
file_lookup_df = pd.DataFrame({'file_name': files})
file_lookup_df = expand_column(file_lookup_df, 'file_name', file_name_components)

In [34]:
file_lookup_df

,make,model,year,msrp,front_wheel_size_in,sae_net_horsepower_rpm,displacement,engine_type,width_max_wo_mirrors_in,height_overall_in,length_overall_in,gas_mileage,drivetrain,passenger_capacity,passenger_doors,body_style,id
0,Ford,Flex,2010,39,19,260,35,6,75,68,201,16,AWD,7,4,4dr,Zza.jpg
1,Chevrolet,Suburban,2011,41,17,320,53,8,79,76,nan,15,RWD,9,4,SUV,hyG.jpg
2,Nissan,Maxima,2011,31,18,290,35,6,73,57,190,19,FWD,5,4,4dr,Ytw.jpg
3,Chevrolet,Silverado 1500,2014,45,20,350,53,8,80,74,nan,16,RWD,5,4,Pickup,Fhi.jpg
4,Dodge,Durango,2019,45,20,290,36,6,75,70,201,18,AWD,6,4,SUV,usz.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64462,Subaru,Forester,2016,29,18,250,20,4,70,68,180,23,AWD,5,4,SUV,KnV.jpg
64463,GMC,Acadia,2011,45,20,280,36,6,78,69,200,16,AWD,7,4,SUV,tug.jpg
64464,Porsche,718,2019,82,20,360,25,4,70,50,173,19,RWD,2,2,Convertible,YpY.jpg
64465,Subaru,Outback,2016,24,17,170,25,4,72,66,189,25,AWD,5,4,SUV,NAc.jpg
64466,Volkswagen,Tiguan,2019,25,17,180,20,4,72,66,185,21,AWD,5,4,SUV,Mzf.jpg